### ISSUE TITLE
`tfenv install latest` returns 403 forbidden

### ISSUE THREAD

**Issue by minamijoyo** [kamatama41/tfenv#27]
Thank you for developing a cool product 😄 

I'm not sure how it used to be, `tfenv install latest` does not seem to be working now.

```
$ tfenv install lastest
install Terraform lastest
get archive from https://releases.hashicorp.com/terraform/lastest/terraform_lastest_darwin_amd64.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0curl: (22) The requested URL returned error: 403 Forbidden
```

The lastest URL may have changed or may have gone 😢

**Comment by kamatama41** [comment]
Hi, thank you for using tfenv!
Probably the version name is wrong, please set `latest`, not `lastest`, thanks 😃

**Comment by minamijoyo** [comment]
Oh... You are right. I'm very sorry 😇

**Comment by kamatama41** [comment]
FYI: I think the error message with invalid version name is a bit confusing, so I've released new version. #28

**Comment by minamijoyo** [comment]
Thank you for adding an error check. It's safe to typo again ☺️
