### ISSUE TITLE
Hashenv?

### ISSUE THREAD

**Issue by kamatama41** [kamatama41/tfenv#36]
Basically HashCorp products' binary is placed in https://releases.hashicorp.com/ so tfenv would be able to be extend to a OSS that manages all installation for them such as 

```
hashenv install terraform 0.9.0
hashenv install packer 0.12.3
```

**Comment by ptierno** [comment]
👍

**Comment by kamatama41** [comment]
I'll close this issue because there is no time and motivation for me to make so far.
