### ISSUE TITLE
Add homebrew installation to README

### ISSUE THREAD

**Issue by pyro2927** [kamatama41/tfenv#37]
I submitted a PR to [homebrew](https://github.com/Homebrew/homebrew-core/pull/10922) to get `tfenv` added.  It can now be installed via:

```bash
$ brew install tfenv
```

Hoping to make this easier for people to install.

**Comment by kamatama41** [comment]
Thank you for the input.
I'll add to README, or, of course, you can create a pull request 😃

**Comment by pyro2927** [comment]
If you're cool waiting until next week I'll make a PR. Away from my computer for a funeral this week.
