### ISSUE TITLE
tfenv install matches when it should not

### ISSUE THREAD

**Issue by timgurney-ee** [kamatama41/tfenv#56]
If I use tfenv to install an older version of terraform then it incorrectly matches a version that is already installed if the installed version has the target version as a substring.

example:

tfenv install '0.9.1'
Terraform v0.9.11 is already installed

**Comment by timgurney-ee** [comment]
Update:

looks like 0.N.1 always fails see complete list below:

tfenv list-remote | while read version; do tfenv install "${version}"; done

Terraform v0.10.0-beta2 is already installed
Terraform v0.10.0-beta1 is already installed
Terraform v0.9.11 is already installed
Terraform v0.9.10 is already installed
Terraform v0.9.9 is already installed
Terraform v0.9.8 is already installed
Terraform v0.9.7 is already installed
Terraform v0.9.6 is already installed
Terraform v0.9.5 is already installed
Terraform v0.9.4 is already installed
Terraform v0.9.3 is already installed
Terraform v0.9.2 is already installed
Terraform v0.9.11 is already installed
Terraform v0.9.0 is already installed
Terraform v0.8.8 is already installed
Terraform v0.8.7 is already installed
Terraform v0.8.6 is already installed
Terraform v0.8.5 is already installed
Terraform v0.8.4 is already installed
Terraform v0.8.3 is already installed
Terraform v0.8.2 is already installed
Terraform v0.8.1 is already installed
Terraform v0.8.0 is already installed
Terraform v0.7.13 is already installed
Terraform v0.7.12 is already installed
Terraform v0.7.11 is already installed
Terraform v0.7.10 is already installed
Terraform v0.7.9 is already installed
Terraform v0.7.8 is already installed
Terraform v0.7.7 is already installed
Terraform v0.7.6 is already installed
Terraform v0.7.5 is already installed
Terraform v0.7.4 is already installed
Terraform v0.7.3 is already installed
Terraform v0.7.2 is already installed
Terraform v0.7.13 is already installed
Terraform v0.7.0 is already installed
Terraform v0.6.16 is already installed
Terraform v0.6.15 is already installed
Terraform v0.6.14 is already installed
Terraform v0.6.13 is already installed
Terraform v0.6.12 is already installed
Terraform v0.6.11 is already installed
Terraform v0.6.10 is already installed
Terraform v0.6.9 is already installed
Terraform v0.6.8 is already installed
Terraform v0.6.7 is already installed
Terraform v0.6.6 is already installed
Terraform v0.6.5 is already installed
Terraform v0.6.4 is already installed
Terraform v0.6.3 is already installed
Terraform v0.6.2 is already installed
Terraform v0.6.16 is already installed
Terraform v0.6.0 is already installed
Terraform v0.5.3 is already installed
Terraform v0.5.1 is already installed
Terraform v0.5.0 is already installed
Terraform v0.4.2 is already installed
Terraform v0.4.1 is already installed
Terraform v0.4.0 is already installed
Terraform v0.3.7 is already installed
Terraform v0.3.6 is already installed
Terraform v0.3.5 is already installed
Terraform v0.3.1 is already installed
Terraform v0.3.0 is already installed
Terraform v0.2.2 is already installed
Terraform v0.2.1 is already installed
Terraform v0.2.0 is already installed
Terraform v0.1.1 is already installed
Terraform v0.1.0 is already installed

**Comment by ben-pubnub** [comment]
I also just hit this. Not a fix, but in the meantime, adding `$` to the end will get you what you want.
```
tfenv install 0.9.1$
```

**Comment by timgurney-ee** [comment]
Perfect that solved the problem - thanks.

**Comment by kamatama41** [comment]
@timgurney-ee @ben-pubnub 
Sorry for late reply and thank you for your report.
This seems a fault of version detection of [here](https://github.com/kamatama41/tfenv/blob/a59cecc66053861cbf71d06cf1fddd948d158094/libexec/tfenv-install#L43).
I'll try fixing (or you can make a PR 💪), thanks.

**Comment by kamatama41** [comment]
Now the bug was fixed. Please update tfenv to the latest, thanks 😃
