### ISSUE TITLE
tfenv: No versions matching '0.9.11' found in remote` after upgrading to MacOS 10.12.6

### ISSUE THREAD

**Issue by hylaride** [kamatama41/tfenv#60]
MacOS 10.12.6 updated curl to 7.54.0 and when running in `tfenv-list-remote` it fails.

 The following command in `tfenv-list-remote` returns nothing:

 ```
curl --tlsv1.2 https://releases.hashicorp.com/terraform/
curl: (35) Unknown SSL protocol error in connection to releases.hashicorp.com:-9836
```

Where as running as in the following, it runs cleanly (note that --tls-max is only available in the latest MacOS 10.12.6 curl - how you would prefer to go about fixing it is up to you, but i'd just let curl negotiate).
```
curl  --tls-max 1.3 https://releases.hashicorp.com/terraform/

<!DOCTYPE html>
<html>
<head>
  <title>Terraform Versions | HashiCorp Releases</title>

BLAH BLAH BLAH
```

My guess is that MacOS 10.12.6 or curl 7.54.0 deprecated some ciphers in TLS 1.2 and the remote isn't supported.

**Comment by kamatama41** [comment]
Thank you for your report.
I'll have a look at it.

**Comment by kkrusedp** [comment]
Ditto,  Im using the brew version 0.5.0 and seeing something similar.  

14:32:47 [kkruse@MacBookPro.local:~] $ tfenv list-remote
14:32:55 [kkruse@MacBookPro.local:~] $
14:33:02 [kkruse@MacBookPro.local:~] $ tfenv install 0.7.2
tfenv: tfenv-install: [ERROR] No versions matching '0.7.2' found in remote

This seems to have occurred after that recent Sierra update like OP mentioned.

**Comment by kkrusedp** [comment]
Actually I also confirmed with the git clone of repo too.  I can work around it manually for now but FYI.   Work around manually just drop the bins to your tfenv/versions/0.7.2/ dir for your platform.

**Comment by jharley** [comment]
@kkrusedp you can just remove `--tls1.2` from the tfenv-list-remote file in libexec as a temporary fix

**Comment by kamatama41** [comment]
Now `--tlsv1.2` option is removed on macOS 10.12.6 (or above).
Please update tfenv to v0.5.2, thanks.

**Comment by kamatama41** [comment]
I'll close this issue, please reopen and comment if curl still doesn't work in your machine .
